#command: bundle exec rails db:chatwoot_prepare
version: "3.8"

services:
  chatwoot-rails:
    image: chatwoot/chatwoot:v4.0.0
    environment:
      RAILS_ENV: "production"
      NODE_ENV: "production"
      INSTALLATION_ENV: "docker"

      SECRET_KEY_BASE: "chave_unica"
      FRONTEND_URL: "http://192.168.1.77:3000"
      ENABLE_ACCOUNT_SIGNUP: "false"

      # Banco e Redis (caso estejam em outro compose ou serviços)
      POSTGRES_HOST: "postgres"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "minha_senha"
      POSTGRES_DATABASE: "chatwoot"
      REDIS_URL: "redis://redis:6379"
      ACTIVE_STORAGE_SERVICE: local

      # Configurações S3/MinIO
      #ACTIVE_STORAGE_SERVICE: "s3_compatible"
      #STORAGE_BUCKET_NAME: "chatwoot"
      #STORAGE_ACCESS_KEY_ID: ""
      #STORAGE_SECRET_ACCESS_KEY: ""
      #STORAGE_REGION: "us-east-1"
      #STORAGE_ENDPOINT: ""
      #STORAGE_FORCE_PATH_STYLE: "true"


      # Exemplo de chave OpenAI (opcional)
      #OPENAI_COMPLETIONS_ENABLED: "true"
      #OPENAI_API_KEY: ""

      # Logs
      RAILS_LOG_TO_STDOUT: "true"
      LOG_LEVEL: "info"

    networks:
      - app_network
    ports:
      - "3000:3000"
    volumes:
      - chatwoot_data:/app/storage
    restart: always
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]

  chatwoot-sidekiq:
    image: chatwoot/chatwoot:v4.0.0
    environment:
      RAILS_ENV: "production"
      NODE_ENV: "production"
      INSTALLATION_ENV: "docker"

      SECRET_KEY_BASE: "chave_unica"
      FRONTEND_URL: "http://192.168.1.77:3000"
      ENABLE_ACCOUNT_SIGNUP: "false"

      POSTGRES_HOST: "postgres"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "minha_senha"
      POSTGRES_DATABASE: "chatwoot"
      REDIS_URL: "redis://redis:6379"
      ACTIVE_STORAGE_SERVICE: local
      #Mesmas configs de MinIO/S3
      #ACTIVE_STORAGE_SERVICE: "s3_compatible"
      #STORAGE_BUCKET_NAME: "chatwoot"
      #STORAGE_ACCESS_KEY_ID: "aeqQmYw9kLU21OpEsog4"
      #STORAGE_SECRET_ACCESS_KEY: "GwHQD8OQ7tOeYXoVEtlL8PdBtl7s022JGUqZ0DpU"
      #STORAGE_REGION: "us-east-1"
      #STORAGE_ENDPOINT: "http://192.168.1.77:9002"
      #STORAGE_FORCE_PATH_STYLE: "true"
      #AWS_REGION: "us-east-1"

      #OPENAI_COMPLETIONS_ENABLED: "true"
      #OPENAI_API_KEY: ""

      RAILS_LOG_TO_STDOUT: "true"
      LOG_LEVEL: "info"

    networks:
      - app_network
    volumes:
      - chatwoot_data:/app/storage
    restart: always
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]

volumes:
  chatwoot_data:
networks:
  app_network:
    external: true
