services:
  redis:
    image: redis:7
    container_name: redis_aula
    command: ["redis-server", "--appendonly", "yes", "--port", "6379"]
    # Caso queira utilizar com senha, utilize esta linha:
    # command: ["redis-server", "--appendonly", "yes", "--port", "6379", "--requirepass", "SENHA_AQUI"]
    networks:
      - app_network
    volumes:
      - redis_data:/data
    restart: always
    # Se quiser expor a porta para acesso externo, descomente a linha abaixo:
    # ports:
    #   - "6379:6379"

volumes:
  redis_data:
    

networks:
  app_network:
    external: true
